import { useEffect } from "react";
import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-toastify/dist/ReactToastify.css";
import '../stylesheet.css'


function MyApp({ Component, pageProps }: any) {
  const pageLayout = Component.layout || ((page: any) => page);

  useEffect(() => {
    require("bootstrap/dist/js/bootstrap");
  }, []);

  return pageLayout(
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
